cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),    
    url(r'^', include('shop.urls', namespace='shop')),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

blogs/models.py
from django.db import models
from django.core.urlresolvers import reverse

from django.utils import timezone
from django.utils.safestring import mark_safe

from markdown_deux import markdown

# Create your models here.
class Blog(models.Model):
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200)
	image = models.ImageField(upload_to='blogs/%Y/%m', blank=True)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
	    return reverse("blogs:detail", kwargs={"slug": self.slug})

	class Meta:
		ordering = ['-timestamp', '-updated']

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

cart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

shop/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.urlresolvers import reverse

from markdown_deux import markdown
# Create your models here.

class Product(models.Model):
  
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                choices=PRODUCT_QUANTITY_CHOICES,
                coerce=int)
    update = forms.BooleanField(required=False,
                initial=False,
                widget=forms.HiddenInput)

blogs/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone

from .models import Blog
# Create your views here.

def blog_list(request):
	today = timezone.now().date()

	paginator = Paginator(queryset_list, 9) # Show 9 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)

	context = {
		"object_list": queryset, 
		"title": "List",
		"page_request_var": page_request_var,
		"today": today,
	}
	return render(request, "blog/blog_list.html", context)


def blog_detail(request, slug=None):
	blog = get_object_or_404(Blog, id=id, slug=slug, available=True)
	context = {
		'title': title,
		'blog': blog,
	}
	return render(request, 'blog/blog_detail.html', context)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart

from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
            'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Product
from cart.forms import CartAddProductForm

# Create your views here.
def product_list(request, category_slug=None):   
    products = Product.objects.filter(available=True)

    paginator = Paginator(products , 9) # Show 9 contacts per page
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        products = paginator.page(paginator.num_pages)

    context = {
        'products': products,
        "page_request_var": page_request_var,
    }
    return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'shop/product/detail.html', context)

templates/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}Pecandu Coffee{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css">
  {% block stylesheet %}{% endblock %}

</head>

<body>
{% block body %}
{% include 'snippet/nav.html' %}

  <div class="py-5">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-7">
          <h2 class="text-primary"><b>Sejarah Pecandu Coffee</b></h2>
          <p class="">Berdirinya Pecandu Coffee diawali pada tahun 2013, ketika pencetusnya Syarif Hidayatullah seorang anggota pecinta alam di Bandung yang diberi kopi Arabica Jawa Barat (Java Preanger) oleh salah seorang seniornya di MAHATALA (Mahasiswa Pencinta
            Alam). Hal tersebut terjadi secara berulang, dari kopi yang dicampur susu sampai kopi murni 100% yang diwarkan. Dari situ pencetus tertarik untuk mengulik dan mencari karakter kopi yang sesuai dengan yang di inginkan. Dan berpikir untuk membuat
            suatu usaha penjualan kopi yang sudah di masak dalam bentuk biji atau sudah serbuk. </p>
          <p class="">Setelah empat tahun lamanya mempelajari seluk-beluk kopi, rencana usaha itu mulai terealisasi di awal tahun 2017. Diambilnya nama pecandu coffee terinspirasi dari pencetus sendiri yang merasa ketagihan saat meminum kopi. Hingga sampai ini Pecandu
            Coffee menjual produk roasted bean coffee dan memiliki outlet di Jl. Margajati NO.12 Cijaura Hilir – Bandung. </p>
        </div>
        <div class="col-md-5 align-self-center">
          <img class="img-fluid d-block w-100 img-thumbnail" src="{% static 'img/slide-0.jpg' %}"> </div>
      </div>
    </div>
  </div>
{% include 'snippet/footer.html' %}
{% endblock body %}
</body>
</html>
    

templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    your shopping cart
{% endblock %}

{% block content %}
 <h1>Your shopping cart</h1>
 <table class="cart">
     <thead>
     <tr>
         <th>Image</th>
         <th>Product</th>
         <th>Quantity</th>
         <th>Unit price</th>
         <th>Price</th>
     </tr>
     </thead>
     <tbody>
        {% for item in cart %}
        {% with product=item.product %}
     <tr>
         <td>
             <a href="{{ product.get_absolute_url }}">
                 <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="">
             </a>
         </td>
         <td>{{ product.name }}</td>
         <td>{{ item.quantity }}</td>
         <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
         <td class="num">Rp {{ item.price }}</td>
         <td class="num">Rp {{ item.total_price }}</td>
     </tr>
     {% endwith %}
     {% endfor %}
     <tr class="total">
         <td>Total</td>
         <td colspan="4"></td>
         <td class="num">Rp {{ cart.get_total_price }}</td>
     </tr>
     </tbody>
 </table>
<p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">Continue shopping</a>
    <a href="#" class="button">Checkout</a>
</p>
{% endblock %}

templates/contact.html
<!DOCTYPE html>
<html>

{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}Pecandu Coffee{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css">
  {% block stylesheet %}{% endblock %}

</head>

<body>
{% block body %}
 {% include 'snippet/nav.html' %}

  <!-- contact us -->
  <div class="py-5 text-white bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1980.2020035941553!2d107.65526544036929!3d-6.961576524037232!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x6ab7c99e0d2740e5!2sPECANDU+COFFEE+Shop!5e0!3m2!1sid!2sid!4v1507760431183"
            width="600" height="450" frameborder="0" style="border:0" allowfullscreen=""></iframe>
        </div>
        <div class="col-md-5">
          <h1 class="text-dark">Contact us</h1>
          <p class="text-dark">We would love to hear from you</p>
          <form>
            <div class="form-group"> <label for="InputName" class="text-dark">Your name</label>
              <input type="text" class="form-control" id="InputName" placeholder="Your name"> </div>
            <div class="form-group"> <label for="InputEmail1" class="text-dark">Email address</label>
              <input type="email" class="form-control" id="InputEmail1" placeholder="Enter email"> </div>
            <div class="form-group"> <label for="Textarea" class="text-dark">Write here</label> <textarea class="form-control" id="Textarea" rows="3" placeholder="Type here"></textarea> </div>
            <button type="submit" class="btn btn-dark">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- footer -->
 {% include 'snippet/footer.html' %}
{% endblock body %}
</body>
</html>
    

templates/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="assets/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="assets/css/style.css" type="text/css"> </head>

<body>
<nav class="navbar navbar-expand-md navbar-dark text-capitalize bg-dark">
    <div class="container">
      <a class="navbar-brand" href="#"><i class="fa d-inline fa-lg fa-coffee"></i><b>  Pecandu Coffee</b></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item bg-dark">
            <a href="#" class="text-light nav-link">Coffee</a>
          </li>
          <li class="nav-item bg-dark">
            <a href="#" class="text-light nav-link">About</a>
          </li>
          <li class="nav-item bg-dark">
            <a href="#" class="text-light nav-link">Contact</a>
          </li>
        </ul>
        <a class="btn navbar-btn ml-2 text-white btn-dark border border-dark btn-lg"><i class="fa d-inline fa-lg fa-cart-plus"></i> </a>
      </div>
    </div>
  </nav>


  <div class="py-5 opaque-overlay" style="background-image: url(&quot;img/banner.jpg&quot;);">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-3 text-white">
          <img class="img-fluid d-block mx-auto mb-5 rounded-circle" src="img/logo.jpg"> </div>
        <div class="col-md-9 text-white align-self-center">
          <h1 class="display-3 mb-4">Image and gradient intro</h1>
          <p class="lead mb-5">Get a fluid web page working on all devices with the Bootstrap 4 grid system.&nbsp;
            <br> </p>
          <a href="#" class="btn btn-lg mx-1 btn-primary">A claim here</a>
          <a href="#" class="btn btn-lg mx-1 btn-secondary">Your call to action</a>
        </div>
      </div>
    </div>
  </div>
  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="breadcrumb" style="margin-bottom:0px;margin-top:0px">
            <li class="breadcrumb-item">
              <a href="#">Home</a>
            </li>
            <li class="breadcrumb-item active">Link</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-light text-dark py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-4 my-3">
          <div class="card">
            <img class="img-fluid" src="img/produk-1.jpg" alt="Card image">
            <div class="card-body">
              <h6 class="card-subtitle text-muted">Support card subtitle</h6>
              <p class="card-text p-y-1">Some quick example text to build on the card title .</p>
              <a href="#" class="card-link">link</a>
              <a href="#" class="card-link">Second link</a>
            </div>
          </div>
        </div>
        <div class="col-md-4 my-3">
          <img class="img-fluid d-block mb-4" src="img/produk-2.jpg">
          <h5><b>Features#2: strawberries</b></h5>
          <p class="mt-1">Integrate it in your toolset. Use Pingendo alongside your favourite code editor, Git client, etc.</p>
        </div>
        <div class="col-md-4 my-3">
          <img class="d-block mb-4 rounded img-fluid" src="img/produk-3.jpg">
          <h5><b>Features#3: blue palette</b></h5>
          <p class="mt-1">Just quality vanilla Bootstrap 4 code. No messy dependencies. For nerds peace of mind.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Previous"> <span aria-hidden="true">«</span> <span class="sr-only">Previous</span> </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">1</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">4</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next"> <span aria-hidden="true">»</span> <span class="sr-only">Next</span> </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- carousel -->
  <div class="py-5 text-white bg-secondary">
    <div class="container">
      <div class="row">
        <div class="align-self-center p-5 col-md-6">
          <h1 class="mb-4">Carousel with controls and captions</h1>
          <p class="mb-5">Get a fluid web page working on all devices with the Bootstrap 4 grid system.&nbsp; Responsive design made intuitive and effective with Pingendo.</p>
          <a class="btn btn-lg btn-outline-light" href="#">View the gallery</a>
        </div>
        <div class="col-md-6 p-0">
          <div id="carousel1" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img src="img/slide-0.jpg" atl="first slide" class="d-block img-fluid w-100">
                <div class="carousel-caption">
                  <h3>Dining room</h3>
                  <p>Good architecture, better food</p>
                </div>
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid w-100" src="img/slide-2.JPG" data-holder-rendered="true">
                <div class="carousel-caption">
                  <h3>Relax area</h3>
                  <p>Take the time to chill</p>
                </div>
              </div>
              <div class="carousel-item">
                <img src="img/slide-1.JPG" class="d-block img-fluid w-100" data-holder-rendered="true">
                <div class="carousel-caption">
                  <h3>Cigar room</h3>
                  <p>Enjoy our fine selection</p>
                </div>
              </div>
              <div class="carousel-item">
                <img class="img-fluid" src="img/slide-3.jpg">
                <div class="carousel-caption">
                  <h2>Title</h2>
                  <p>Description</p>
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carousel1" role="button" data-slide="prev"> <span class="carousel-control-prev-icon" aria-hidden="true"></span> <span class="sr-only">Previous</span> </a>
            <a class="carousel-control-next" href="#carousel1" role="button" data-slide="next"> <span class="carousel-control-next-icon" aria-hidden="true"></span> <span class="sr-only">Next</span> </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- footer -->
  <div class="py-5 bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-8 my-3">
          <h1 class="display-4 text-white text-md-left text-center">Spread the love&nbsp;</h1>
        </div>
        <div class="col-md-4  text-center align-self-center">
          <a href="https://www.facebook.com/" target="_blank"><i class="fa fa-fw fa-facebook fa-3x text-white mx-3"></i></a>
          <a href="https://twitter.com/" target="_blank"><i class="fa fa-fw fa-twitter fa-3x text-white mx-3"></i></a>
          <a href="https://www.instagram.com/" target="_blank"><i class="fa fa-fw fa-instagram fa-3x text-white mx-3"></i></a>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-dark text-white">
    <div class="container">
      <div class="row">
        <div class="p-4 col-md-3">
          <h2 class="mb-4 text-secondary">Pingendo</h2>
          <p class="text-white">A company for whatever you may need, from website prototyping to publishing</p>
        </div>
        <div class="p-4 col-md-3">
          <h2 class="mb-4 text-secondary">Mapsite</h2>
          <ul class="list-unstyled">
            <a href="#" class="text-white">Home</a>
            <br>
            <a href="#" class="text-white">About us</a>
            <br>
            <a href="#" class="text-white">Our services</a>
            <br>
            <a href="#" class="text-white">Stories</a>
          </ul>
        </div>
        <div class="p-4 col-md-3">
          <h2 class="mb-4">Contact</h2>
          <p>
            <a href="tel:+246 - 542 550 5462" class="text-white"><i class="fa d-inline mr-3 text-secondary fa-phone"></i>+246 - 542 550 5462</a>
          </p>
          <p>
            <a href="mailto:info@pingendo.com" class="text-white"><i class="fa d-inline mr-3 text-secondary fa-envelope-o"></i>info@pingendo.com</a>
          </p>
          <p>
            <a href="https://goo.gl/maps/AUq7b9W7yYJ2" class="text-white" target="_blank"><i class="fa d-inline mr-3 fa-map-marker text-secondary"></i>365 Park Street, NY</a>
          </p>
        </div>
        <div class="p-4 col-md-3">
          <h2 class="mb-4 text-light">Subscribe</h2>
          <form>
            <fieldset class="form-group text-white"> <label for="exampleInputEmail1">Get our newsletter</label>
              <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email"> </fieldset>
            <button type="submit" class="btn btn-outline-secondary">Submit</button>
          </form>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3">
          <p class="text-center text-white">© Copyright 2017 denihhandoko - All rights reserved. </p>
        </div>
      </div>
    </div>
  </div>
  <script src="assets/js/jquery-3.2.1.min.js" ></script>
  <script src="assets/js/popper.js/1.11.0/umd/popper.min.js" ></script>
  <script src="assets/js/bootstrap.min.js" ></script>
</body>

</html>

templates/shop/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{% block title %}Pecandu Coffee{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css">
  {% block stylesheet %}{% endblock %}

</head>

<body>
{% block body %}
{% include 'snippet/nav.html' %}
{% include 'snippet/banner.html' %}

  {% block content %}
  {% endblock %}

{% include 'snippet/carousel.html' %}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% include 'snippet/footer.html' %}
{% endblock body %}
</body>
</html>
    

templates/shop/product/detail.html
{% load static %}


{% include 'snippet/nav.html' %}

{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <img class="img-fluid d-block" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
        </div>
        <div class="col-md-6">         
          <h5><b>{{ product.name }}</b></h5>   
          <p class="price">Harga : Rp. {{ product.price }}</p>
          <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="Add to cart">
          <p>{{ product.description|linebreaks }}</p></td>
        </div>        
      </div>
    </div>
  </div>
  <br/>
  <br/>
  <br/>
  <br/>

{% endblock %}

{% include 'snippet/footer.html' %}

templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  
{% endblock %}

{% block content %}

  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="breadcrumb" style="margin-bottom:0px;margin-top:0px">
            <li class="breadcrumb-item">
              <a href="/">Home</a>
            </li>
            <li class="breadcrumb-item active">Link</li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="bg-light text-dark py-2">
    <div class="container">
      <div class="row">
        {% for product in products %}
        <div class="col-md-4 my-3">
          <div class="card">
            <img class="img-fluid" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="Card image">
            <div class="card-body">
              <h5><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
              <p class="card-text p-y-1">Harga @ Rp. {{ product.price }}</p>
              <p class="card-text p-y-1">Stok barang {{ product.stock }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

<!-- pagination -->
<div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Previous"> <span aria-hidden="true">Previous</span> <span class="sr-only"></span> </a>
            </li>

            <li class="page-item">
             {{ object_list.number }}{{ object_list.paginator.num_pages }}.
            </li>
  
            <li class="page-item">
              <a class="page-link" href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" aria-label="Next"> <span aria-hidden="true">Next</span> <span class="sr-only"></span> </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/snippet/banner.html
{% load static %}
<div class="py-5 opaque-overlay" style="background-image: url(&quot;{% static 'img/banner.jpg' %}&quot;);">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-3 text-white">
          <img class="img-fluid d-block mx-auto mb-5 rounded-circle" src="{% static 'img/logo.jpg' %}"> </div>
        <div class="col-md-9 text-white align-self-center">
          <h1 class="display-3 mb-4">Pecandu Coffee</h1>
          <p class="lead mb-5">Roasted bean coffee.&nbsp;
          <br> </p>
        </div>
      </div>
    </div>
  </div>